services:

  webpack:

    build:
      context: .
    volumes:
     - ./src:/project/src
     - ./babel.config.json:/project/babel.config.json
     - ./package.json:/project/package.json
     - ./tsconfig.json:/project/tsconfig.json
     - ./webpack.config.js:/project/webpack.config.js