services:

  webpack:

    build:
      context: .
    volumes:
     - ./src:/project/src
     - ./.eslintrc.json:/project/.eslintrc.json
     - ./package.json:/project/package.json
     - ./tsconfig.json:/project/tsconfig.json